// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("TaskID");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            TaskID = new Guid("fde50f74-5bf6-4125-ab35-832a1a987486"),
                            CreatedDate = new DateTime(2024, 5, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bieg na 10 km",
                            Status = "Pending",
                            Title = "Bieganie"
                        },
                        new
                        {
                            TaskID = new Guid("56e7ad83-5296-4aa0-82a7-43cb3b9128ed"),
                            CreatedDate = new DateTime(2024, 5, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nauka na kolokwium z Mongo",
                            Status = "InProgress",
                            Title = "Kolokwium bazy"
                        },
                        new
                        {
                            TaskID = new Guid("9b8de07f-ecac-4a14-9943-cb797d47f962"),
                            CreatedDate = new DateTime(2024, 5, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Znalezienie pracy jako .NET Developer",
                            Status = "InProgress",
                            Title = "Praca"
                        },
                        new
                        {
                            TaskID = new Guid("0b411a9a-0b64-4c70-96b5-f2025ea21ad9"),
                            CreatedDate = new DateTime(2024, 5, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zrobienie formy na lato :)",
                            Status = "Completed",
                            Title = "Zrobienie formy"
                        },
                        new
                        {
                            TaskID = new Guid("e2a3c4b5-d6e7-f8a9-b0c1-d2e3f4a5b6c7"),
                            CreatedDate = new DateTime(2024, 5, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kupić mleko, chleb, jajka",
                            Status = "Pending",
                            Title = "Zakupy"
                        },
                        new
                        {
                            TaskID = new Guid("f1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"),
                            CreatedDate = new DateTime(2024, 5, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dokończyć projekt Task Tracker",
                            Status = "InProgress",
                            Title = "Projekt ASP.NET"
                        },
                        new
                        {
                            TaskID = new Guid("a0b9c8d7-e6f5-a4b3-c2d1-e0f9a8b7c6d5"),
                            CreatedDate = new DateTime(2024, 5, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Opanować EF Core przed egzaminem",
                            Status = "Pending",
                            Title = "Nauka Entity Framework"
                        },
                        new
                        {
                            TaskID = new Guid("b1c2d3e4-f5a6-b7c8-d9e0-f1a2b3c4d5e6"),
                            CreatedDate = new DateTime(2024, 5, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Omówić rozwój kariery .NET",
                            Status = "Completed",
                            Title = "Spotkanie z mentorem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
